version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "helloWorld"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-8xek0p011u4l"
s3_prefix = "helloWorld"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

